version: '3.7'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local
  redis:
    driver: local
  elasticsearch:
    driver: local

services:

  ### Workspace Utilities Container ###########################

  workspace:
    image: abenevaut/laradock-workspace:${APP_TAG:-latest}
    build:
      context: ./laradock/workspace
      cache_from:
        - abenevaut/laradock-workspace:latest
      args:
        - PHP_VERSION=${DOCKER_PHP_VERSION}
        - LARADOCK_PHP_VERSION=${DOCKER_PHP_VERSION}
        - INSTALL_SUBVERSION=false
        - INSTALL_XDEBUG=true
        - INSTALL_PHPDBG=false
        - INSTALL_BLACKFIRE=true
        - INSTALL_SSH2=false
        - INSTALL_GMP=false
        - INSTALL_SOAP=false
        - INSTALL_LDAP=false
        - INSTALL_IMAP=false
        - INSTALL_MONGO=false
        - INSTALL_AMQP=false
        - INSTALL_PHPREDIS=false
        - INSTALL_MSSQL=false
        - INSTALL_NODE=true
        - NPM_REGISTRY=false
        - INSTALL_YARN=false
        - INSTALL_NPM_GULP=false
        - INSTALL_NPM_BOWER=false
        - INSTALL_NPM_VUE_CLI=false
        - INSTALL_DRUSH=false
        - INSTALL_DRUPAL_CONSOLE=false
        - INSTALL_AEROSPIKE=false
        - AEROSPIKE_PHP_REPOSITORY=false
        - INSTALL_V8JS=false
        - COMPOSER_GLOBAL_INSTALL=false
        - COMPOSER_REPO_PACKAGIST=false
        - INSTALL_WORKSPACE_SSH=true
        - INSTALL_LARAVEL_ENVOY=false
        - INSTALL_LARAVEL_INSTALLER=false
        - INSTALL_DEPLOYER=true
        - INSTALL_PRESTISSIMO=fale
        - INSTALL_LINUXBREW=false
        - INSTALL_MC=false
        - INSTALL_SYMFONY=false
        - INSTALL_PYTHON=false
        - INSTALL_IMAGE_OPTIMIZERS=false
        - INSTALL_IMAGEMAGICK=true
        - INSTALL_TERRAFORM=false
        - INSTALL_DUSK_DEPS=true
        - INSTALL_PG_CLIENT=false
        - INSTALL_SWOOLE=false
        - INSTALL_LIBPNG=false
        - INSTALL_IONCUBE=false
        - PUID=1000
        - PGID=1000
        - CHROME_DRIVER_VERSION=2.32
        - NODE_VERSION=11
        - YARN_VERSION=latest
        - DRUSH_VERSION=8.1.17
        - TZ=${DOCKER_PROJECT_TZ}
        - BLACKFIRE_CLIENT_ID=
        - BLACKFIRE_CLIENT_TOKEN=
    volumes:
      - ${DOCKER_PROJECT_PATH}:/var/www:cached
    extra_hosts:
      - "dockerhost:10.0.75.1"
    ports:
      - "${DOCKER_WORKSPACE_PUBLIC_PORT}:22"
    tty: true
    environment:
      - PHP_IDE_CONFIG="serverName=${APP_NAME}"
    networks:
      - frontend
      - backend

  ### PHP-FPM Container #######################################

  php-fpm:
    image: abenevaut/laradock-php-fpm:${APP_TAG:-latest}
    build:
      context: ./laradock/php-fpm
      cache_from:
        - abenevaut/laradock-php-fpm:latest
      args:
        - PHP_VERSION=${DOCKER_PHP_VERSION}
        - LARADOCK_PHP_VERSION=${DOCKER_PHP_VERSION}
        - INSTALL_XDEBUG=true
        - INSTALL_PHPDBG=false
        - INSTALL_BLACKFIRE=true
        - INSTALL_SSH2=false
        - INSTALL_SOAP=false
        - INSTALL_IMAP=false
        - INSTALL_MONGO=false
        - INSTALL_AMQP=false
        - INSTALL_MSSQL=false
        - INSTALL_ZIP_ARCHIVE=false
        - INSTALL_BCMATH=false
        - INSTALL_GMP=false
        - INSTALL_PHPREDIS=false
        - INSTALL_MEMCACHED=false
        - INSTALL_OPCACHE=false
        - INSTALL_EXIF=true
        - INSTALL_AEROSPIKE=false
        - AEROSPIKE_PHP_REPOSITORY=false
        - INSTALL_MYSQLI=false
        - INSTALL_PGSQL=false
        - INSTALL_PG_CLIENT=false
        - INSTALL_TOKENIZER=false
        - INSTALL_INTL=false
        - INSTALL_GHOSTSCRIPT=false
        - INSTALL_LDAP=false
        - INSTALL_SWOOLE=false
        - INSTALL_IMAGE_OPTIMIZERS=false
        - INSTALL_IMAGEMAGICK=true
        - INSTALL_CALENDAR=false
        - INSTALL_FAKETIME=false
        - INSTALL_IONCUBE=false
    volumes:
      - ./laradock/php-fpm/php${DOCKER_PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ${DOCKER_PROJECT_PATH}:/var/www:cached
    expose:
      - "${DOCKER_PHPFPM_PORT}"
    extra_hosts:
      - "dockerhost:10.0.75.1"
    environment:
      - PHP_IDE_CONFIG="serverName=${APP_NAME}"
      - DOCKER_HOST=tcp://docker-in-docker:2375
      - FAKETIME=-0
    depends_on:
      - workspace
    networks:
      - backend

  ### Apache Server Container #################################

  apache2:
    image: abenevaut/laradock-apache2:${APP_TAG:-latest}
    build:
      context: ./laradock/apache2
      cache_from:
        - abenevaut/laradock-apache2:latest
      args:
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=${DOCKER_PHPFPM_PORT}
        - PHP_UPSTREAM_TIMEOUT=60
        - DOCUMENT_ROOT=/var/www/public/
    volumes:
      - ${DOCKER_PROJECT_PATH}:/var/www:cached
      - ${DOCKER_STORAGE_PATH}/apache2/logs:/var/log/apache2
      - ${DOCKER_STORAGE_PATH}/apache2/sites:/etc/apache2/sites-available
    ports:
      - "${DOCKER_APACHE_PUBLIC_HTTP_PORT}:80"
      - "${DOCKER_APACHE_PUBLIC_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  ### MySQL Container #########################################

  mysql:
    image: abenevaut/laradock-mysql:${APP_TAG:-latest}
    build:
      context: ./laradock/mysql
      cache_from:
        - abenevaut/laradock-mysql:latest
      args:
        - MYSQL_VERSION=${DOCKER_MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - TZ=${DOCKER_PROJECT_TZ}
    volumes:
      - ./laradock/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${DOCKER_STORAGE_PATH}/mysql:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - backend

  ### Mailhog Container #########################################

  mailhog:
    image: abenevaut/laradock-mailhog:${APP_TAG:-latest}
    build:
      context: ./laradock/mailhog
      cache_from:
        - abenevaut/laradock-mailhog:latest
    ports:
      - "${MAIL_PORT}:1025"
      - "${DOCKER_MAILHOG_PUBLIC_HTTP_PORT}:8025"
    networks:
      - backend
      - frontend
